name: python-ci

on:
  push:
    paths:
      - "hesiod_py/**"
      - "pyproject.toml"
      - "poetry.lock"
      - "mkdocs.yml"
      - "docs/**"
      - "tests/**"
      - ".github/workflows/python-ci.yml"
  pull_request:
    paths:
      - "hesiod_py/**"
      - "pyproject.toml"
      - "poetry.lock"
      - "mkdocs.yml"
      - "docs/**"
      - "tests/**"
      - ".github/workflows/python-ci.yml"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pipx install poetry==1.8.3

      - name: Configure Poetry
        run: poetry config virtualenvs.create true

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run Ruff
        run: poetry run ruff check .

      - name: Run Black
        run: poetry run black --check .

      - name: Run MyPy
        run: poetry run mypy .

      - name: Run Tests
        run: poetry run pytest
